#! /bin/bash

cd "${0%/*}"/.. || exit $?

STD_CLASS_DEFS="std-class-defs.lua"
STD_CLASS_DEFS_NEW="$STD_CLASS_DEFS.new"
GENED_CLASS_DEFS="lua/generated_class_definitions.lua"

view_diff() {
	./lex/make-standard-class-definitions.lua >"$STD_CLASS_DEFS_NEW" || return $?
	if cmp -s "$STD_CLASS_DEFS" "$STD_CLASS_DEFS_NEW" ; then
		return 0
	fi
	echo "New version differs [Press Enter]" && read 
	diff -Naur "$STD_CLASS_DEFS" "$STD_CLASS_DEFS_NEW" | less -S
	echo "Adjust it and run '$0' to check again, or (if you're satisfied) run '$0 --continue'"
	return 1
}

if [ "$1" = "-v" ] ; then
	view_diff
	exit $?
fi

if [ "$1" = "--continue" ] ; then
	mv "$STD_CLASS_DEFS_NEW" "$STD_CLASS_DEFS" || exit $?
	git rebase --continue || exit $?
	exit 0
fi

if ! [ -e lex/Makefile ] ; then
	./lex/make-standard-class-definitions.lua >"$STD_CLASS_DEFS" || exit $?
	exit 0
fi

make -C lex || exit $?

I="--include /usr/include/c++/6.3.0"
I="--include /usr/lib/clang/4.0.0/include"

if [ -e lex/config.json ] ; then
	./lex/lua-exporter $I --config lex/config.json -s src/ -o "$GENED_CLASS_DEFS" >lex/e.log 2>&1 || exit $?
else
	./lex/lua-exporter $I -s src/ -o "$GENED_CLASS_DEFS" >lex/e.log 2>&1 || exit $?
fi

# Just for information: remove comments what (and why) something has been skipped generated by lex
grep -E '^ *--' <lua/generated_class_definitions.lua >>lex/e.log
sed -i '/^ *--/d' lua/generated_class_definitions.lua

view_diff || exit $?

exit 0
